### ISSUE TITLE
Passing function to imported ejs 

### ISSUE THREAD

**Issue by bspatil0001** [difelice/ejs-loader#31]
Earlier without webpack ejs-loader, using the lodash

ejs template was
```
<h1>USER NAME</h1>
<%- func(userName) %>
```

```
import inputTemplate from 'template.ejs'
var templateOptionsObj = {
      imports: {
        func: function func(str) {
          return str.toUpperCase();
        }
      }
    }

    var template = _.template(inputTemplate, templateOptionsObj);
    $('#divID').append(template(data));

```

Now i am using ejs-loader with webpack

  ```
import inputTemplate from 'template.ejs' // is already returning exicuted value of  _.template(inputTemplate);

  var templateOptionsObj = {
      imports: {
        func: function func(str) {
          return str.toUpperCase();
        }
      }
    }

  var template = inputTemplate(data, templateOptionsObj); // is not woking

```

i am not able to pass my function to the ejs after importing.

How do i need to import my function into the ejs after importing ejs.

**Comment by AtofStryker** [comment]
@bspatil0001 this likely is an issue because `ejs-loader` takes `imports` into account only during loader options and functions as the template compiler.

It looks like you are trying to compile the template yourself. If that is the case, you might want to pass `imports` as a loader option. Or, you can always pass func as a interpolation variable into the template and invoke the function inside the template.
